import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Main.module.css'
import Logo from '../components/Logo'
import Links from '../components/Links'
import Contatos from '../components/Contatos'
import Rodape from '../components/Rodape'

const inter = Inter({ subsets: ['latin'] })

const description = `Site desenvovido em Next JS para o Frigolima supermercados. Uma aplicação SPA, visando responsividade e facilidade no uso e manejo dos links que vão na bio do Instagram.`

export default function Home() {
  return (
    <>
      <Head>
        <title>Frigolima Supermercados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Marcos Henrique Marcarini Junior" />
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />  
      </Head>

      <main className={styles.main}>
        <Logo />
        <Links />
        <Contatos />
        <Rodape />
      </main>
    </>
  )
}
